Attribute VB_Name = "M�dulo4"
'=============Restablecer formulas===============00
Public Nivel_Tension as string

public sub Restablecer_Configurador()
    with thisworkbook.sheets("Configurador")
        'Caracteristicas
            .Range("BS36").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;2;FALSO)"
            .Range("BS39").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;3;FALSO)"
            .Range("BS42").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;4;FALSO)"
            .Range("BS45").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;5;FALSO)"
            .Range("BS48").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;6;FALSO)"
            .Range("BS51").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;7;FALSO)"
            .Range("BS54").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;8;FALSO)"
            .Range("BS57").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;9;FALSO)"
            .Range("BS60").FormulaLocal = "=BUSCARV('Hoja2'!B82;'Hoja2'!A84:J96;10;FALSO)"
        'Fila 76
            .Range("CI76").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("CZ76").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("DQ76").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("EH76").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("EY76").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("FP76").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("GG76").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("GX76").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("HO76").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;3;FALSO);"""")"
            .Range("IF72").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;3;FALSO);"""")"
        'Fila 80
            .Range("CI80").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("CZ80").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("DQ80").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("EH80").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("EY80").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("FP80").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("GG80").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("GX80").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;4;FALSO);"""")"
            .Range("HO80").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;4;FALSO);"""")" 
            .Range("IF80").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;4;FALSO);"""")"
        'Fila 84
            .Range("CI84").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("CZ84").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("DQ84").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("EH84").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("EY84").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("FP84").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("GG84").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("GX84").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("HO84").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;5;FALSO);"""")"
            .Range("IF84").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;5;FALSO);"""")"    
        'Fila 88
            .Range("CI88").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("CZ88").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("DQ88").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("EH88").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("EY88").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("FP88").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("GG88").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("GX88").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("HO88").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;6;FALSO);"""")"
            .Range("IF88").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;6;FALSO);"""")" 
        'Fila 92
            .Range("CI92").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("CZ92").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("DQ92").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("EH92").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("EY92").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("FP92").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("GG92").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("GX92").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("HO92").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;7;FALSO);"""")"
            .Range("IF92").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;7;FALSO);"""")"    
        'Fila 96  
            .Range("CI96").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("CZ96").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("DQ96").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("EH96").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("EY96").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("FP96").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("GG96").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("GX96").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;8;FALSO);"""")"    
            .Range("HO96").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;8;FALSO);"""")"
            .Range("IF96").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;8;FALSO);"""")"
        'Fila 100
            .Range("CI100").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("CZ100").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("DQ100").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("EH100").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("EY100").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;9;FALSO);"""")" 
            .Range("FP100").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("GG100").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("GX100").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("HO100").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;9;FALSO);"""")"
            .Range("IF100").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;9;FALSO);"""")"
        'Fila 104
            .Range("CI104").FormulaLocal = "=SI.ERROR(BUSCARV(CI72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("CZ104").FormulaLocal = "=SI.ERROR(BUSCARV(CZ72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("DQ104").FormulaLocal = "=SI.ERROR(BUSCARV(DQ72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("EH104").FormulaLocal = "=SI.ERROR(BUSCARV(EH72;Hoja2!B1:L44;10;FALSO);"""")"    
            .Range("EY104").FormulaLocal = "=SI.ERROR(BUSCARV(EY72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("FP104").FormulaLocal = "=SI.ERROR(BUSCARV(FP72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("GG104").FormulaLocal = "=SI.ERROR(BUSCARV(GG72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("GX104").FormulaLocal = "=SI.ERROR(BUSCARV(GX72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("HO104").FormulaLocal = "=SI.ERROR(BUSCARV(HO72;Hoja2!B1:L44;10;FALSO);"""")"
            .Range("IF104").FormulaLocal = "=SI.ERROR(BUSCARV(IF72;Hoja2!B1:L44;10;FALSO);"""")"
        ' limpiar celdas y referencias
        .Range("CI69:IF69").value = ""
        .Range("CI72:IF72").value = "" 
        .Range("CI114:IF170").value = ""      
    end with
end sub    